module.exports={
    connection:{
        'host':'localhost',
        'user':'root',
        'password':''
    },
    'database':'myportfolio',
    'table1':'users',
    'table2':'skills',
    'table3':'technology',
    'table4':'technologies',
    'table5':'soft_skills',
    'table6':'skills',
    'table7':'portfolios',
    'table8':'experiences',
    'table9':'contact'
}